### ISSUE TITLE
It didn't get to the speed

### ISSUE THREAD

**Issue by RayTracingON** [ddm999/ClubmanSharp#39]
I use the subaru's car and it always hit the wall.Did I set wrong?
![捕获](https://user-images.githubusercontent.com/110779956/204476649-1c9db038-73eb-4823-bf77-5804158e861a.PNG)

**Comment by Photon-Phoenix** [comment]
> I use the subaru's car and it always hit the wall.Did I set wrong? ![捕获]

Your screenshot's lack of a nitrous indicator and the SH/SH tyres suggests you didn't tune the WRX to the settings on the wiki.  Please tune the WRX to the settings at this page:

https://github.com/ddm999/ClubmanSharp/wiki/WRX

**Comment by RayTracingON** [comment]
Thanks!I got it and it did well
