### ISSUE TITLE
Keep showing error

### ISSUE THREAD

**Issue by tenki33** [ddm999/ClubmanSharp#42]
first I want to thank you for the excellent work of this.Saving great deal of time.
Now I've been using this for about a week.after about 3 days the later version 1.1 came out I've downloaded it but kept using the old version since all went well like usual.today it started showing error message as below:
"Error during Simulator interface client update.Exception details below (this part is orginally Chinese same as my system language but can roughly translate into this:An existing connection was forcibly closed by the remote host)"
so I switched to the latest version and the problem remain still.
What seems to be the problem and how to fix it?
big thanks :)

**Comment by ddm999** [comment]
Usually this means your Playstation's IP address has changed: check the IP address again and update it in ClubmanSharp

**Comment by tenki33** [comment]
indeed it did！thank you！
