### ISSUE TITLE
GTO Tuning and bahaviour

### ISSUE THREAD

**Issue by adamwwa** [ddm999/ClubmanSharp#43]
After update 1.25 a lot of tunes have changed PP. Current tune for GTO gives result above 550PP. 
PP limit can be achieved with slight power reduction 97-98 and this is enough to win race, case is that GTO just after start hit right side of the wall. I don't know if this is caused by change in tune or this is general problem with this car, problem don't exist in Impreza.

**Comment by Photon-Phoenix** [comment]
Could you please screenshot your tuning pages and GT Auto parts and wheels installed?  I've refreshed the GTOs engine and reselected wheels and aero parts to ensure the tune is still compatible with 1.27, the GTO is still ending up with 549.95 PP.

**Comment by adamwwa** [comment]
This is totally my fault - I forgot small detail which was racing clutch and flywheel - this make a trick to lower down PP.
