### ISSUE TITLE
Suggestion for Achieving Clean Race Result

### ISSUE THREAD

**Issue by sritify** [ddm999/ClubmanSharp#45]
Hi, first of all, thanks for creating this awesome program to glitch credit for GT7!
I noticed that as long as in the first lap if our car can pass through those 4 cars successfully, the problem always happens in the last lap.
What if the program tune down the speed a little bit in the last lap, so it won't even catch up those 4 rival cars again? 
I know it may take 20-30 more seconds in order to do this, but it will have a higher probability of getting a clean race run, and getting 100000 instead of 70000 CR.  In long term, i think it can generate more profit on average.

What do you think?

**Comment by ddm999** [comment]
This already exists! Reduce the "Max Throttle" setting in the Settings tab.
245 is usually fine, if I remember correctly.

This applies from laps 3 to 5.

**Comment by sritify** [comment]
Brilliant! Thanks for the prompt response!
