### ISSUE TITLE
FAQ "reduce the Max Throttle setting to artificially slow the bot down"

### ISSUE THREAD

**Issue by peterliuwei** [ddm999/ClubmanSharp#47]
Hi Folks, I've read through FAQ about the isse at the end of each race.

how do I adjust the Throtlle? can't find anything related in the car settings. can some shed some lights?

**Comment by ddm999** [comment]
It's in the "Settings" tab of the app :)
![image](https://user-images.githubusercontent.com/8524741/221012422-e7d30d00-537e-46e6-b845-1ca568fac862.png)

**Comment by peterliuwei** [comment]
Thank you! will give a try shortly. appreciated for your help!

**Comment by peterliuwei** [comment]
I am having issue at the end of each lap, the WRX crashs into the ramp each time :( still couldn't figure out what to do.

**Comment by ddm999** [comment]
Most likely your car isn't tuned exactly as expected.

Check everything mentioned here:
https://github.com/ddm999/ClubmanSharp/wiki/WRX

If you think it's all correct and you still have the issue, post screenshots of your cars tuning screen (like the images in the Tuning options section) so we can be sure that's not the issue

**Comment by peterliuwei** [comment]
Thanks, I've gone through this number of times, will post screenshot as soon I get back to home.

**Comment by peterliuwei** [comment]
I've tried to reduce the throttle to 250, but the issue remains. I've posted a screenshot of where it happens and the turning settings. It looks the same as your instruction. 

Could you please help? thank you!

![Screenshot 2023-02-24 132708](https://user-images.githubusercontent.com/48641085/221062129-0310a8f7-20da-4e68-be6d-aa8c78e94c1d.png)
![Screenshot 2023-02-24 132743](https://user-images.githubusercontent.com/48641085/221062150-c5a08e1e-0a28-43cd-9075-6408ce210430.png)
![Screenshot 2023-02-24 132400](https://user-images.githubusercontent.com/48641085/221062155-f49f1400-5549-417b-9fa8-0a8cc9c619ad.png)
![Screenshot 2023-02-24 132510](https://user-images.githubusercontent.com/48641085/221062163-554ffc5a-51bf-494b-bb56-ca17ad83fa9c.png)

**Comment by Photon-Phoenix** [comment]
From the 3rd image, you appear to have additional driving assists on which are hindering the performance of clubmansharp. (Braking/Steering Assists)

Please toggle off any and all driving assists except for ABS and try again.

**Comment by peterliuwei** [comment]
Thank you so much! the frist lap is perfect!!!. appreciated for your help!! :)
