### ISSUE TITLE
PS5 system and ps remote play updated, now it doesnt work

### ISSUE THREAD

**Issue by Ericjt11** [ddm999/ClubmanSharp#48]
PS5 system and ps remote play updated, now it doesnt worked.
Before updated it works very well. Please do something
Thank you very much!

**Comment by Photon-Phoenix** [comment]
> PS5 system and ps remote play updated, now it doesnt worked. Before updated it works very well. Please do something Thank you very much!

Could you provide any error messages ClubmanSharp is giving, or if none, describe what ClubmanSharp is getting stuck on?

**Comment by Ericjt11** [comment]
> > PS5 system and ps remote play updated, now it doesnt worked. Before updated it works very well. Please do something Thank you very much!
> 
> Could you provide any error messages ClubmanSharp is giving, or if none, describe what ClubmanSharp is getting stuck on?

There is no error message, only nothing happened when I press start as usual

**Comment by ddm999** [comment]
Can you make sure that there's no controller connected to your PC on launching Remote Play?

That's the usual issue that leads to this: if there's a physical controller connected, Remote Play will just ignore the fake controller that ClubmanSharp uses.

**Comment by Ericjt11** [comment]
> Can you make sure that there's no controller connected to your PC on launching Remote Play? (ie. fully close Remote Play, unplug any controllers, start Remote Play again)
> 
> That's the usual issue that leads to this: if there's a physical controller connected, Remote Play will just ignore the fake controller that ClubmanSharp uses.

yes，I'm sure. 
It worked very well about 2 hours ago, and I updated PS5 system ,then Remote Play automatically updated. Nothing else changed.
I have reinstalled Remote Play, restarted PC,and everything I can do.But it still not work.

**Comment by Ericjt11** [comment]
> 
OK, thank you for your help! 
This is a great project！

**Comment by Photon-Phoenix** [comment]
> > 
> 
> OK, thank you for your help! This is a great project！

In the meantime, the workaround is to install Remote play 5.5.0 and use the version patcher.  Links to both provided below: (the file name for the remote play installer says PS4 but it works for 5 and 4)

https://cdn.discordapp.com/attachments/969221686564122694/1083013175852675144/ps4-remote-play-5.5.0.08250-installer.exe

https://github.com/xeropresence/remoteplay-version-patcher/releases

https://github.com/xeropresence/remoteplay-version-patcher/blob/master/README.md

**Comment by Ericjt11** [comment]
It worked!! Thank you very much！

**Comment by Goooler** [comment]
You can try Chiaki, see https://github.com/ddm999/ClubmanSharp/issues/54#issuecomment-1646453656.

**Comment by ddm999** [comment]
Closed as v1.2.0 should now be better at patching and the [section on the help page](https://github.com/ddm999/ClubmanSharp/wiki#update-for-remote-play-v60) has been updated.
