### ISSUE TITLE
[GT7 1.31] PP Changes have affected the car set-up

### ISSUE THREAD

**Issue by tanago** [ddm999/ClubmanSharp#50]
The set-up is now 580.99 PP which is above the allowed for the event 550

**Comment by ddm999** [comment]
Myself and Photon are working on new cars for post-update, this will also likely require a ClubmanSharp update to change the driving data

I'll close this when it's all done and you can start using the bot again :)

**Comment by ddm999** [comment]
New tunes are available and they work with the old data! Check the wiki page for them :)
