### ISSUE TITLE
Having trouble install older version remote play

### ISSUE THREAD

**Issue by tenki33** [ddm999/ClubmanSharp#53]
After I click the"install patched remote play" button,I get this box
![1](https://github.com/ddm999/ClubmanSharp/assets/121053892/dc5a7670-0345-4b9d-8fb1-2d45b3eeca42)

after clicking OK button I get this one immidiately
![2](https://github.com/ddm999/ClubmanSharp/assets/121053892/185456e8-e735-4c81-9c4b-c4058e0f8ccc)

then I sometimes get a remoteplay.exe in the clubmansharp folder,nothing happens when I click it so I tried the original remoteplay.exe,click start with the right address filled in,nothing happenes.(most of the time,I get a remoteplay.exe in the folder when I click the "install patched remote play" button,but it disappear after the second box)

**Comment by ddm999** [comment]
See the https://github.com/ddm999/ClubmanSharp/wiki#update-for-remote-play-v60 section:
- if it gets left in the ClubmanSharp folder you need to move that over the top of your Remote Play install
- if that still doesn't work (it just doesn't for some people, not 100% figured out why yet) then uninstall Remote Play, use the linked installer to get v5.5 and then patch it with the linked patcher

**Comment by Goooler** [comment]
You can try Chiaki, see https://github.com/ddm999/ClubmanSharp/issues/54#issuecomment-1646453656.

**Comment by ddm999** [comment]
Closed as v1.2.0 should now be better at patching and the [section on the help page](https://github.com/ddm999/ClubmanSharp/wiki#update-for-remote-play-v60) has been updated.
Open another issue if you're still stuck / you get stuck again :)
