### ISSUE TITLE
Can we support Chiaki?

### ISSUE THREAD

**Issue by Goooler** [ddm999/ClubmanSharp#54]
Replace older remote play with Chiaki.

**Comment by Goooler** [comment]
I tried, it works well! And if we can note this in wiki?

**Comment by ddm999** [comment]
Added a mention on the wiki homepage at https://github.com/ddm999/ClubmanSharp/wiki#remote-play-alternative
As noted, we won't provide any support with the additional setup it requires (account id & registering console pin)

**Comment by Goooler** [comment]
Thanks!
