### ISSUE TITLE
Remote Play doesn't work anymore (5.5 Patched) - 14/09/23

### ISSUE THREAD

**Issue by ta20d** [ddm999/ClubmanSharp#59]
Hello, today remote play (5.5 patched) stop to work.
 I follow up the info in the topic about this problem and I tried to uninstall and reinstall that but I experiencing a problem into installing 5.5 remote play, windows show up an error and doesn't let the installer work. How I can deal with that ?

**Comment by ta20d** [comment]
Thank you so much! now seems to work very well

**Comment by ddm999** [comment]
Going to close this issue as you've resolved it manually & v1.2.0 patcher now should fix this too :)
