### ISSUE TITLE
Migrate patcher to include RpCtrlWrapper.dll & a v6.5 reporting exe

### ISSUE THREAD

**Issue by ddm999** [ddm999/ClubmanSharp#60]
Also possibly add a text file noting the original & patched version.
(how to find original version easily?)

Oh, and download them compressed. 🙂

Files are:
https://cdn.discordapp.com/attachments/957051217366908928/1151842747964203158/PS_Remote_Play.zip

Should help those who reported #48, #53, #59
(but those won't be solved until we migrate to a library which supports new Remote Play without patching, or ViGEm.Bus gets support... which isn't likely after it's copyright troubles)

**Comment by ddm999** [comment]
cheating: use this set of files instead:
https://cdn.discordapp.com/attachments/1003642204960596069/1151876659641864202/PS_Remote_Play.zip

which report as v100.5 😎 so the update check should always fail

**Comment by Pierre-French** [comment]
Hi,
I tried tu execute (on several Windows 10 PCs) the RemotePlay.exe included in 
https://cdn.discordapp.com/attachments/1003642204960596069/1151876659641864202/PS_Remote_Play.zip
reporting v100.5 and it never started ... even when running it in administrator mode ; no error message but nothing happens. 
Do you have a solution ?
Many thanks for your help and excuse me for my poor english, i'm french ...

**Comment by Photon-Phoenix** [comment]
> Hi, I tried tu execute (on several Windows 10 PCs) the RemotePlay.exe included in https://cdn.discordapp.com/attachments/1003642204960596069/1151876659641864202/PS_Remote_Play.zip reporting v100.5 and it never started ... even when running it in administrator mode ; no error message but nothing happens. Do you have a solution ? Many thanks for your help and excuse me for my poor english, i'm french ...

You need to overwrite the files in the Remote Play installation folder with the files from the zip.

Usually the installation location of remote play is at
C:\Program Files (x86)\Sony\PS Remote Play\

**Comment by Pierre-French** [comment]
I didn't understand that I had to replace the remote player files with yours
 I just did it and everything is back to normal and running perfectly.
A big thank-you !
Is there a way to know what release of RemotePlayer is installed on my PC ?
