### ISSUE TITLE
A new button in 1.38, "Weather Radar", prevents matches from starting。

### ISSUE THREAD

**Issue by Kitakana** [ddm999/ClubmanSharp#61]
A new button "Weather Radar" has been added to the pre-race menu since 1.38. This button may confuse ClubmanSharp and failed to start at the first time.

**Comment by Photon-Phoenix** [comment]
> A new button "Weather Radar" has been added to the pre-race menu since 1.38. This button may confuse ClubmanSharp and failed to start at the first time.

An update to address this along with other remote play issues will be rolling out it's ready.  In the meantime, enter the race manually then press Start on ClubmanSharp.
ClubmanSharp will pause and restart the race, then continue normally as before.

**Comment by ta20d** [comment]
I remote complete working with photon-phoenix procedure.
