### ISSUE TITLE
Support ticket: Hard to win race

### ISSUE THREAD

**Issue by Goooler** [ddm999/ClubmanSharp#63]
Use the latest 1.2.0, but seems hard to win the competation?

<img src="https://github.com/ddm999/ClubmanSharp/assets/10363352/8157c767-31d6-4138-9b81-996907a112b0" width="70%" height="70%">

**Comment by Photon-Phoenix** [comment]
> Use the latest 1.2.0, but seems hard to win the competation?
> 
> <img alt="" width="70%" height="70%" src="https://user-images.githubusercontent.com/10363352/277123169-8157c767-31d6-4138-9b81-996907a112b0.png">

Screenshot your tune, assist settings, controller settings, and in game race screen, please.

**Comment by Goooler** [comment]
This works well with GT7 1.45 udpate.
