### ISSUE TITLE
PP Ratings have changed and the tunes are invalid with v1.49

### ISSUE THREAD

**Issue by tanago** [ddm999/ClubmanSharp#67]
The tunes are obsolete with the updated PP calculations.

**Comment by DMack-11** [comment]
![image](https://github.com/user-attachments/assets/95efdcab-4ae0-479e-bceb-52d468db7171)

For the Evo IV, set both front and rear tyres to sports:hard, change ballast to 190kg with -44 positioning and set the power restrictor to 94.

This isn't a proper fix and could probably be improved on, but it should keep you running.

**Comment by ddm999** [comment]
We're expecting suspension changes coming soon in a hotfix, so there's not going to be anything properly concrete until that comes out. 
Photon's been working a little though, so there might be a reduced number of less stable tunes available soon-ish as a holdover.

**Comment by Photon-Phoenix** [comment]
Wiki has been updated with tunes for 1.49. These are most likely updating once the suspension changes again next update.

**Comment by bubbleprotein** [comment]
PP Ratings have changed again

**Comment by Photon-Phoenix** [comment]
Wiki has been updated with tunes for 1.50.
