### ISSUE TITLE
not work on 1.54, some thing wrong get status

### ISSUE THREAD

**Issue by swordiel** [ddm999/ClubmanSharp#68]

**Comment by gakaki** [comment]
yes i got race menu stop

**Comment by swordiel** [comment]
> yes i got race menu stop

this update version support ps5pro, seems changes a lot, otherwise the script had been working stable for more than 1year :)

**Comment by Anchp** [comment]
Because 1.54 has one more step to retry.

**Comment by Anchp** [comment]
Because 1.54 meun is different. After finsh race, you need to select 'retry' then select 'start' to start a new race with the same AI.

**Comment by ddm999** [comment]
Resolved by https://github.com/ddm999/ClubmanSharp/releases/tag/v1.3.0
(for some reason I thought it'd automatically close this oops)
