### ISSUE TITLE
Can you please release a version for MacOS?

### ISSUE THREAD

**Issue by weihaopeng** [ddm999/ClubmanSharp#71]
can it run on MacOS?

**Comment by Photon-Phoenix** [comment]
> can it run on MacOS?

ClubmanSharp's dependency ViGEmBus does not have a Mac version, however there's a way to run this on Macs:

In Parallels or VirtualBox, you need to install Windows 10 or 11 and set the network adapter type to Bridged. A license key is not needed for Windows install in Parallels or VirtualBox.

From there you install ViGEmBus and Remote Play, then have ClubmanSharp patch the Remote Play executable. ClubmanSharp will run as intended, even if there is no video output from Remote Play.
